### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by BiancaMe** [BiancaMe/JSCapstone#4]
There's 2 people in our team,

link to the project issues page

https://github.com/BiancaMe/JSCapstone/projects/1

**Comment by BiancaMe** [comment]
Done by Ronald

**Comment by mj-e-boc** [comment]
https://github.com/BiancaMe/JSCapstone

-There is 2 people in our team

**Comment by OyePriscilla** [comment]
Hi @BiancaMe and @mj-e-boc 👍 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Set up Kanban board ✔️ 
Assigned task to group members ❎ 

## Required Changes ♻️

- [ ] For the sake of clarity, kindly assign all the tasks fairly with all the members of the group. You need to decide who is Student A and Student B. 
<img width="305" alt="Untitled" src="https://github.com/BiancaMe/JSCapstone/assets/103386183/df92be3a-06e7-4869-b943-9186e483954d">

- [ ] Please I noticed that one card is missing from the board, kindly add it to move forward. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
